title: "HC26 Senior Project - Ethan Abdoo"
description: "Proposal for my senior project"

# url: "https://EthanAbdoo3.github.io"
baseurl: "/HC26-Abdoo-Ethan-Senior-Project"

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-seo-tag

remote_theme: pages-themes/midnight@v0.2.0